name: Destroy environment

on: 
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}  

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.1
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3.0.0
            with:
              terraform_version: 1.6.6
          - name: Terraform Init
            run: |
              terraform init -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
              -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
              -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
              -backend-config="key=${{ secrets.UAT_KEY }}" \
              -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}"
          - name: Terraform Destroy
            run: |
              terraform destroy -auto-approve   
