name: 'Terraform GitHub Actions'
on:
    push:
        branches:
            - dev

env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3.0.0
          with:
            terraform_version: 1.6.6
        - name: Terraform Init
          run: |
            terraform init -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="key=${{ secrets.KEY }}" \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}"
        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan

        - name: Terraform Apply
          run: terraform apply -auto-approve